/* eslint-disable @typescript-eslint/triple-slash-reference */
/// <reference path="./broad-phase.d.ts" />
/// <reference path="./collide-circle.d.ts" />
/// <reference path="./collide-edge.d.ts" />
/// <reference path="./collide-polygon.d.ts" />
/// <reference path="./collision.d.ts" />
/// <reference path="./distance.d.ts" />
/// <reference path="./dynamic-tree.d.ts" />
/// <reference path="./time-of-impact.d.ts" />
