/* eslint-disable @typescript-eslint/triple-slash-reference */
/// <reference path="./distance-joint.d.ts" />
/// <reference path="./friction-joint.d.ts" />
/// <reference path="./gear-joint.d.ts" />
/// <reference path="./joint.d.ts" />
/// <reference path="./motor-joint.d.ts" />
/// <reference path="./mouse-joint.d.ts" />
/// <reference path="./prismatic-joint.d.ts" />
/// <reference path="./pulley-joint.d.ts" />
/// <reference path="./revolute-joint.d.ts" />
/// <reference path="./rope-joint.d.ts" />
/// <reference path="./weld-joint.d.ts" />
/// <reference path="./wheel-joint.d.ts" />
