/* eslint-disable @typescript-eslint/triple-slash-reference */
/// <reference path="./chain-and-circle-contact.d.ts" />
/// <reference path="./chain-and-polygon-contact.d.ts" />
/// <reference path="./circle-contact.d.ts" />
/// <reference path="./contact-solver.d.ts" />
/// <reference path="./contact.d.ts" />
/// <reference path="./edge-and-circle-contact.d.ts" />
/// <reference path="./edge-and-polygon-contact.d.ts" />
/// <reference path="./polygon-and-circle-contact.d.ts" />
/// <reference path="./polygon-contact.d.ts" />
